name: Generate targeted PRs

on:
  workflow_dispatch:
    inputs:
      target_pr:
        description: 'The URL of the PR that contains the release to target for updates'
        required: false
        type: string

jobs:
  scala-steward:
    permissions:
      contents: read
      pull-requests: read
    name: scala-steward
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      
      - uses: guardian/setup-scala@c9f10cca1674ecb2ae7ee739786ef9f0cdb9d07c # v2.0.0
      
      - name: Write a custom scala-steward configuration to target a specific artifact
        env:
          TARGETED_RELEASES_GITHUB_APP_CLIENT_ID: 214238
          TARGETED_RELEASES_GITHUB_APP_PRIVATE_KEY: ${{ secrets.SCALA_STEWARD_APP_PRIVATE_KEY }}
        run: sbt "run ${{ inputs.target_pr }} targeted-scala-steward.conf"
        
      - name: Execute Scala Steward
        uses: scala-steward-org/scala-steward-action@6162b21b93d4be314a61ce0462fd026630132fee # v2.96.0
        with:
          github-app-id: 214238
          github-app-installation-id: 26822732
          github-app-key: ${{ secrets.SCALA_STEWARD_APP_PRIVATE_KEY }}
          repo-config: targeted-scala-steward.conf
          other-args: "--add-labels"
