name: Public Repos Scala Steward

on:
  schedule:
    - cron: "55 9-18 * * MON-FRI"
  # Provide support for manually triggering the workflow via GitHub.
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-scala-steward.yml
    with:
      app_id: 214238
      app_installation_id: 26822732
    secrets:
      private_key: ${{ secrets.SCALA_STEWARD_APP_PRIVATE_KEY }}
